_wandb:
    value:
        cli_version: 0.25.1
        e:
            8lu9w2pzudidya41j55quzzse6x5ed1a:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                codePath: /Users/saicharanreddy/Documents/MLOPS/MLOps/Labs/Experiment_Tracking_Labs/W&B/Lab2.ipynb
                codePathLocal: Lab2.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "293199572992"
                email: saicherry006@gmail.com
                executable: /opt/homebrew/opt/python@3.10/bin/python3.10
                git:
                    commit: ffb07d3ab4693354b50bb8d882a73bafd69162bc
                    remote: git@github.com:saicharan-cpu/MLOps.git
                host: Sais-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/saicharanreddy/Documents/MLOPS/MLOps/Labs/Experiment_Tracking_Labs/W&B/Lab2.ipynb
                python: CPython 3.10.15
                root: /Users/saicharanreddy/Documents/MLOPS/MLOps/Labs/Experiment_Tracking_Labs/W&B
                startedAt: "2026-04-11T15:37:28.978802Z"
                writerId: 8lu9w2pzudidya41j55quzzse6x5ed1a
        m:
            - "1": batch/batch_step
              "6":
                - 3
              "7": []
            - "2": batch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 7
                - 13
                - 16
                - 38
                - 39
                - 61
            "4": 3.10.15
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": darwin-arm64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 64
decay_rate:
    value: 0.9
decay_steps:
    value: 1000
dense_units:
    value: 256
dropout:
    value: 0.3
epochs:
    value: 10
layer_1_size:
    value: 64
layer_2_size:
    value: 128
learn_rate:
    value: 0.001
optimizer:
    value: adam
sample:
    value: 60000
