input {
  file {
    path => "/Users/saicharanreddy/Documents/MLOPS/MLOps/Labs/ELK_Labs/Lab2_ELK_Setup_Mac/training.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} - %{LOGLEVEL:loglevel} - %{GREEDYDATA:message}" }
  }

  grok {
    match => { "message" => "F1 Score: %{NUMBER:f1_score}" }
    overwrite => [ "f1_score" ] 
  }

  grok {
    match => { "message" => "False Positive Rate: %{NUMBER:fpr}" }
    overwrite => [ "fpr" ]
  }
  grok {
    match => { "message" => "False Negative Rate: %{NUMBER:fnr}" }
    overwrite => [ "fnr" ]
  }

  # Rename fields to create columns
  mutate {
    rename => {
      "timestamp" => "log_timestamp"
      "loglevel" => "log_level"
      "message" => "log_message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    index => "logstash-training"
    user => "elastic"
    password => "jZDNWMpRsjRClp_b9Et_"
    ssl_enabled => true
    ssl_verification_mode => "none"
  }
  stdout {
    codec => rubydebug { metadata => false }
  }
}
